### ISSUE TITLE
[Feat] 마이페이지 사용자 기본 정보, 선호 차량 화면 UI 구현

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web#18]
## 📔 Description

마이페이지에서 볼 수 있는 사용자의 기본 정보와 선호 차량을 보여주는 UI 구현

## 🐈 Todo

- [x] 사용자 기본 정보 UI 구현
- [x] 기본 정보 내에서의 닉네임 변경 UI 구현
- [x] 사용자의 선호 차량 UI 구현
