### ISSUE TITLE
[Feat] 홈 화면의 차량 조회 컴포넌트 UI 구현

### ISSUE THREAD

**Issue by seolbotdae** [YU-RentCar/yurentcar-fe-web#25]
## 📔 Description

<img width="593" alt="스크린샷 2023-05-26 오후 7 47 32" src="https://github.com/YU-RentCar/yurentcar-fe-web/assets/54520200/b7f838ed-a5e6-407c-9614-0404c733d812">

- 차량 조회 화면의 UI를 구현하기 위해 이슈 개설
- 여기서, 차량 조회 화면이란, 지점, 시간 선택 이후의 화면을 말함.

## 🐈 Todo

- [x] 시간과 지점을 알려주는 컴포넌트 UI 제작
- [x] 사용자가 선호하는 차량을 검색하는 컴포넌트 UI 제작
- [x] 공지사항을 보여주는 컴포넌트 UI 제작
- [x] 검색된 차량을 보여주는 컴포넌트 UI 제작

<br><br>
