### ISSUE TITLE
[Feat] 마이페이지 전체 컨텐츠 컴포넌트 세로 비율 조정

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web#26]
## 📔 Description

- 각 컨텐츠들이 보여질 컴포넌트들의 세로 비율을 퍼센트 혹은 뷰포트를 기준으로 설정
- 그 결고로 결과 뷰포트 혹은 화면의 가로 비율을 줄일수록 컨텐츠들이 깨지고 제대로 보여지지 않는 점을 발견

## 🐈 Todo

- [x] 사용자 기본 정보 UI 세로 비율 조정
- [x] 사용자 선호 차량 옵션 UI 세로 비율 조정
- [x] 사용자 이용 내역 UI 세로 비율 조정
- [x] 사용자 면허 정보 UI 세로 비율 조정
- [x] 사용자 계정 관리 UI 세로 비율 조정
