### ISSUE TITLE
[Feat] 마이페이지 각 컨텐츠 별 필요한 팝업 UI 구현

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web#28]
## 📔 Description

- 기존의 마이페이지들은 단순히 기본적이거나 요약된 정보들만을 보여줌
- 각 컨텐츠별로 상세 정보들을 볼 수 있는 트리거인 버튼을 눌렀을 때 보여지는 팝업 UI 를 구현

## 🐈 Todo

- [x] 닉네임 중복 확인 결과 알림 UI 구현
- [x] 닉네임 변경 알림 UI 구현
- [x] 차량 선호 옵션 변경 알림 UI 구현
- [x] 포인트 사용/적립 내역 팝업 UI 구현
- [x] 예약 내역 팝업 UI 구현
- [x] 예약 후기 작성 팝업 UI 구현
