### ISSUE TITLE
[Feat] 홈 이용 시간 선택, 지점 선택 화면 줄어든 UI 구현

### ISSUE THREAD

**Issue by seolbotdae** [YU-RentCar/yurentcar-fe-web#29]
## 📔 Description
홈 이용 시간 선택, 지점 선택 화면이 검색하기를 클릭 할 시 작은 창으로 바뀌기 때문에
작은 창에 해당되는 UI를 추가 구현

## 🐈 Todo

- [x] 홈 이용 시간 선택, 지점 선택 화면이 줄어든 형태의 UI 구현
- [x] 줄어든 형태의 시간, 지점 선택 화면을 다시 펼치는 기능 구현
- [ ] 펼치거나 줄일 경우의 애니메이션 기능 구현
