### ISSUE TITLE
[Refactor] 홈 화면 컴포넌트 제작과 기존 컴포넌트 UI 수정

### ISSUE THREAD

**Issue by seolbotdae** [YU-RentCar/yurentcar-fe-web#39]
## 📔 Description

리액트 라우터 연결 시, 컴포넌트가 명확하게 분리되지 않아 라우터 연결에 문제가 있기 때문에 이슈 생성.

Home.js 파일에 홈 입장시 나타날 컴포넌트를 구현하고, 컴포넌트를 명확하게 분리하여 라우팅을 수월하게 하는 것이 목표이다.

## 🐈 Todo

- [x] Nav.js 수정
- [x] Home.js 구현
- [x] 라우트를 함에 따라 생기는 하위 컴포넌트의 분리, 제작
- [x] 사용자 선호 차량 검색 리스트를 체크박스로 변경
