### ISSUE TITLE
[Refactor] 마이페이지 로직, UI 수정 및 소셜 로그인 하이퍼링크 추가

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web#40]
## 📔 Description

- 백엔드 서버와 테스트를 시작하면서 사용자 기본 정보 로직에서 추가 구현 혹은 수정이 필요해졌음
- 검색 조건의 다양성을 증가시키기 위해 차량 선호 조건을 다중 선택 가능하게 되면서 UI 수정이 필요해짐
- 소셜 로그인을 수행하기 위해 백엔드 서버가 제공해주는 하이퍼링크 추가
 

## 🐈 Todo

- [x] 마이페이지 사용자 기본 정보 로직 & UI 수정
- [x] 차량 선호 조건 UI 수정
- [x] 소셜 로그인 버튼 하이퍼링크 추가
