### ISSUE TITLE
[Feat] 마이페이지 axios & redux 를 이용한 로직 구현

### ISSUE THREAD

**Issue by yh-project** [YU-RentCar/yurentcar-fe-web#47]
## 📔 Description

- axios 와 redux 의 도입으로 기존의 로직 수정
- 사용자 기본 정보 외에 로직 구현
- state 변수들 redux 도입에 맞게 세팅

## 🐈 Todo

- [x] 사용자 기본 정보 로직 수정
- [x] 선호 차량 옵션 로직 구현
- [x] 내역 조회 팝업들에 대한 로직 구현
- [x] 면허 & 계정 관리 세부 내용, 팝업들에 대한 로직 구현
