### ISSUE TITLE
[Feat] 차량 리스트를 클릭 시 팝업이 나타나는 기능 구현

### ISSUE THREAD

**Issue by seolbotdae** [YU-RentCar/yurentcar-fe-web#59]
## 📔 Description

차량 검색을 성공하여 차량 리스트를 클릭 시, 팝업이 나타나는 기능을 구현하기 위한 이슈

## 🐈 Todo

- [x] 리스트의 항목을 클릭하면, 팝업이 표시된다.
- [x] 팝업이 클릭되면, 서버에서 세부 정보를 받아온다.
- [x] 리스트를 클릭하면 로컬 스토리지에 저장이 된다.
- [x] 팝업 내부의 UI를 구현한다.
- [x] 팝업 예약하기 버튼을 누를 시, store에 필요한 정보 저장
