### ISSUE TITLE
[Docs] README PRMerge 상세 설명 추가

### ISSUE THREAD

**Issue by seolbotdae** [YU-RentCar/yurentcar-fe-web#7]
## 📔 Description
README 문서에 PR을 통해 커밋을 할 경우 적용해야할 내용과 제목 작성법이 작성되어 있지 않고,
이슈 종류 중 PRMerge 에 대한 자세한 설명을 추가하기 위해 이슈 생성

## 🐈 Todo

- [x] README PR 커밋 제목, 내용 작성법 추가
- [x] 이슈 종류 PRMerge 에 대해 더 자세한 설명 추가
- [x] Labels 중 PRMerge 에 대해 설명 추가
